version: '3.8'


services:
  gateway:
      image: openmrs/sigdep3-gateway
      build:
       context: ./gateway
      restart: "unless-stopped"
      depends_on:
        - sigdep3-frontend
        - sigdep3-backend
      ports:
        - "80:80"
  
  sigdep3-frontend:
    image: openmrs/sigdep3-frontend
    build:
        context: ./sigdep3/frontend
    restart: "unless-stopped"
    environment:
      SPA_PATH: /openmrs/spa
      API_URL: /openmrs
      SPA_CONFIG_URLS: /openmrs/spa/ozone-frontend-config.json
      SPA_DEFAULT_LOCALE:
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      timeout: 5s
    depends_on:
      - sigdep3-backend
    volumes:
      - ./sigdep3/frontend/ozone-frontend-config.json:/usr/share/nginx/html/ozone-frontend-config.json
      - ./sigdep3/frontend:/usr/share/nginx/html/sigdep

  sigdep3-backend:
    image: openmrs/sigdep3-backend
    build:
       context: ./sigdep3
    restart: "unless-stopped"
    depends_on:
       sigdep3-db:
          condition: service_healthy
    environment:
      OMRS_CONFIG_AUTO_UPDATE_DATABASE: "false"
      OMRS_CONFIG_CREATE_TABLES: "false"
      OMRS_CONFIG_CONNECTION_SERVER: sigdep3-db
      OMRS_CONFIG_CONNECTION_USERNAME: ${OPENMRS_DB_USER:-root}
      OMRS_CONFIG_CONNECTION_PASSWORD: ${OPENMRS_DB_PASSWORD:-root}
      OMRS_CONFIG_CONNECTION_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      OMRS_CONFIG_CONNECTION_EXTRA_ARGS: "&autoReconnect=true&sessionVariables=default_storage_engine%3DInnoDB&useUnicode=true&characterEncoding=UTF-8&useSSL=false&requireSSL=false"
      OMRS_CONFIG_HAS_CURRENT_OPENMRS_DATABASE: "true"
      # OMRS_CONFIG_MODULE_WEB_ADMIN: "true"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/openmrs"]
      timeout: 5s
    volumes:
      - openmrs-data:/openmrs/data
    ports:
      - "8080:8080"
      - "1044:1044"

  sigdep3-db:
    image: library/mysql:5.6
    restart: unless-stopped    
    hostname: sigdep3-db
    container_name: sigdep3-db
    command: "mysqld \
              --character-set-server=utf8 \
              --collation-server=utf8_general_ci \
              --max_allowed_packet=1G \
              --default-authentication-plugin=mysql_native_password \
              --sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION"
    environment:
      MYSQL_DATABASE: "openmrs"
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    volumes:
      - ./configs/sigdep3/mysql.cnf:/etc/mysql/conf.d/custom.cnf  # mysql config preconfigured to allow binlog/debezium
      - ./configs/sigdep3/init-db:/docker-entrypoint-initdb.d
      
      # uncomment to persist the volumes on the Host file system
      # - .db/sigdep3:/var/lib/mysql 
      # - db-data:/var/lib/mysql
    ports:
      - "3307:3306"

volumes:
  openmrs-data: ~
  db-data: ~
  