---
- name: Ping host
  hosts: myhosts
  become: yes
  remote_user: ubuntu
  vars:
    ansible_ssh_private_key_file: /Users/macbookm1/.ssh/id_rsa
  tasks:
    - name: Stop Docker project
      command: docker compose stop sigdep3
      args:
        chdir: /home/ubuntu/code/SIDEP-3-Docker-Setup

    - name: Start Docker project
      command: docker compose up 
      args:
        chdir: /home/ubuntu/code/SIDEP-3-Docker-Setup
